### ISSUE TITLE
Fix broken links in FAQ

### ISSUE THREAD

**Issue by shanegiffordweb** [nathaneastwood/fablore#23]
Many FAQ answers link to specific card pages and reference some of the card flavor text. Those card pages have been removed so the links in the FAQ are broken. I'd suggest linking to another web page with the relevant information if it's no longer hosted on site.

**Comment by nathaneastwood** [comment]
Thanks @shanegiffordweb. I just corrected (hopefully) all of them. Let me know if there are any I missed.
